package namoo.board.dom2.pr.ws.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-04-17T11:03:02.940+09:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", name = "BoardUserWs")
@XmlSeeAlso({ObjectFactory.class})
public interface BoardUserWs {

    @RequestWrapper(localName = "registerUser", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.RegisterUser")
    @WebMethod
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.RegisterUserResponse")
    public void registerUser(
        @WebParam(name = "boardUserJson", targetNamespace = "")
        java.lang.String boardUserJson
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUserWithEmail", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.FindUserWithEmail")
    @WebMethod
    @ResponseWrapper(localName = "findUserWithEmailResponse", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.FindUserWithEmailResponse")
    public namoo.board.dom2.pr.ws.proxy.DcBoardUser findUserWithEmail(
        @WebParam(name = "userEmail", targetNamespace = "")
        java.lang.String userEmail
    );

    @RequestWrapper(localName = "removeUserWithEmail", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.RemoveUserWithEmail")
    @WebMethod
    @ResponseWrapper(localName = "removeUserWithEmailResponse", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.RemoveUserWithEmailResponse")
    public void removeUserWithEmail(
        @WebParam(name = "userEmail", targetNamespace = "")
        java.lang.String userEmail
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.FindAllUsers")
    @WebMethod
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://proxy.ws.pr.dom2.board.namoo/", className = "namoo.board.dom2.pr.ws.proxy.FindAllUsersResponse")
    public java.util.List<namoo.board.dom2.pr.ws.proxy.DcBoardUser> findAllUsers();
}
